### PR TITLE
date datetime helper

### PR DESCRIPTION
**Pull request by umer-mehmood**

### CODE REVIEW

**Comment by planetarydev** [comment]
Hello Umer,
thanks for this new helper. It looks good to me.
Please remove the lines that we dont need.

```javascript
this.$expr = new SQLBuilder.SQLPredefined.StringValueParam(sql);
this.$format = new SQLBuilder.SQLPredefined.StringValueParam(sql);
```

You only need to to declare them if your syntax has used them like:

```
this.Types({
  String: { syntax: this.Syntax('DATE(<value-param>, $expr[, $format])') },
});

**Comment by umer-mehmood** [comment]
Yes, I have removed the extra code which is not used in the helper. PR is
updated. Thanks
Regards,

Umer Mehmood

NorthBay

Direct: +92 3234971359

umer.mahmood@northbaysolutions.net <faheem.khan@northbaysolutions.net>

www.Northbaysolutions.com <http://www.northbaysolutions.com/>

**Comment by planetarydev** [comment]
THANKS!

**Comment by umer-mehmood** [comment]
Hello,

I have a use case in which we want to use $count operator on a column value
and compare the result to any numeric value. And i am not able to use
$where helper to accommodate the $count helper.

E.g.

Select * from table1
Where count(column) = 10

**Comment by umer-mehmood** [comment]
In addition to this, if i want to cast any column type while using it in
where.

E.g.
Select * from table1
Where cast(date) = '2019-09-01'

Also i have to cater this kind of use case.

**Comment by planetarydev** [comment]
One thing ahead - please open an new issue for further questions. So anybody can find if he got the same problem/question.

Using the count-function inside the where clause will be a little bit tricky. You have to use the `anyExpr` helper and it works like this:

```javascript
sql.build({
  $select: {
    $from: 'people',
    $where: {
      $and: [
        { $anyExpr: { $count: '*', $eq: 10 } }
      ]
    }
  }
});
```

[https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/anyExpr](https://github.com/planetarydev/json-sql-builder2/tree/master/sql/helpers/misc/anyExpr)
Here you will find an example for the having clause.

**Comment by planetarydev** [comment]
I have opened an new issue #26 
Please have a look.

**Pull request merged**
